### ISSUE TITLE
classes / styles

### ISSUE THREAD

**Issue by o7n** [andrewicarlson/nova-link-field#1]
It would be cool if we could pass some class attributes or styles as well.

**Comment by simonhamp** [comment]
@andrewicarlson will you be creating a new release with this addition?

**Comment by andrewicarlson** [comment]
@simonhamp just did, very sorry for the delay. Thanks for your help on this!

https://github.com/andrewicarlson/nova-link-field/releases/tag/v1.1.0
https://packagist.org/packages/carlson/nova-link-field#v1.1.0
